# permissions for end users to edit santips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: santip-editor-role
rules:
- apiGroups:
  - prueba.my.domain
  resources:
  - santips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prueba.my.domain
  resources:
  - santips/status
  verbs:
  - get
